title: "Natasha Naima Hussain"
email: natasha1434@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Natasha Hussain is a university Math and Computer Science student. 
baseurl: "/" 
url: "https://NatashaNaima.github.io/" 
twitter_username: NatashaNaima
github_username:  NatashaNaima

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
